CALLBACK_INICIO = 'inicio_jornada'
CALLBACK_DESCANSAR = 'descansar'
CALLBACK_FICHAR = 'fichar'
CALLBACK_IMPUTAR = 'imputar'
CALLBACK_PROYECTOS = 'proyectos'
CALLBACK_NO_IMPUTAR = 'no_imputar'

ENDPOINT_FICHAJE = '/fichar_redirect'
ENDPOINT_JORNADA = '/jornada'
ENDPOINT_FICHAR = '/fichar'

COMMAND_START = 'start'
COMMAND_STOP = 'stop'
COMMAND_STATUS = 'status'
COMMAND_FICHA = 'ficha'
COMMAND_JORNADA = 'jornada'
COMMAND_LOGIN = 'login'
COMMAND_AUTO = 'auto'
COMMAND_IMPUTA = 'imputa'
